# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(3, '三级目录'), (1, '一级目录'), (2, '二级目录')], default=1, help_text='类型级别', verbose_name='类型级别'),
        ),
    ]
