# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180707_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='parent_categorry',
            new_name='parent_category',
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(2, '二级目录'), (1, '一级目录'), (3, '三级目录')], default=1, help_text='类型级别', verbose_name='类型级别'),
        ),
    ]
