# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180713_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级目录'), (3, '三级目录'), (2, '二级目录')], default=1, help_text='类型级别', verbose_name='类型级别'),
        ),
    ]
