# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='trande_no',
            new_name='trade_no',
        ),
    ]
