# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180707_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='pay_script',
            new_name='post_script',
        ),
    ]
