# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180707_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='num',
            new_name='nums',
        ),
    ]
