# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180706_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLevingMessage',
            new_name='UserLeavingMessage',
        ),
    ]
